version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres-db-teacherapp
    environment:
      POSTGRES_DB: teacherapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.data
    ports:
      - 5432:5432

volumes:
  db-data: